// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA5Sx0YS0tVFChYT_32zbbBM0HLAYqBd8',
    appId: '1:966367199063:web:604a373ccd48aea402c812',
    messagingSenderId: '966367199063',
    projectId: 'one-chat-app-61876',
    authDomain: 'one-chat-app-61876.firebaseapp.com',
    storageBucket: 'one-chat-app-61876.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnlIkgx9_IN7_XVPMctU2kQ7OXKbcYtI8',
    appId: '1:966367199063:android:1cb496243d24891f02c812',
    messagingSenderId: '966367199063',
    projectId: 'one-chat-app-61876',
    storageBucket: 'one-chat-app-61876.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2iAQ0dPE66T00NilKyuhKU0PsQo4BZDg',
    appId: '1:966367199063:ios:ce96b590663b0c5d02c812',
    messagingSenderId: '966367199063',
    projectId: 'one-chat-app-61876',
    storageBucket: 'one-chat-app-61876.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2iAQ0dPE66T00NilKyuhKU0PsQo4BZDg',
    appId: '1:966367199063:ios:ce96b590663b0c5d02c812',
    messagingSenderId: '966367199063',
    projectId: 'one-chat-app-61876',
    storageBucket: 'one-chat-app-61876.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA5Sx0YS0tVFChYT_32zbbBM0HLAYqBd8',
    appId: '1:966367199063:web:b41c44b85f2c516402c812',
    messagingSenderId: '966367199063',
    projectId: 'one-chat-app-61876',
    authDomain: 'one-chat-app-61876.firebaseapp.com',
    storageBucket: 'one-chat-app-61876.appspot.com',
  );
}
